### ISSUE TITLE
macOS Catalina does not allow to capture the screen (+ fix)

### ISSUE THREAD

**Issue by interactivetech** [BoboTiG/python-mss#134]
General information:

* OS name: _macOS Catalina_
* OS version: __ 10.15.1__
* OS architecture: _64 bits_
* Resolutions:
    * Retina Monitor: _2560 x 1600_
* Python version: _Python 3.6.7_
* MSS version: __4.0.3__

### Description of the warning/error

I run a basic example of capturing a screenshot:
```
import mss

with mss.mss() as sct:
    filename = sct.shot(mon=-1, output='fullscreen.png')
    print(filename)
```
And this is the result: fullscreen.png, none of the open windows are captured:
![fullscreen](https://user-images.githubusercontent.com/5833510/71136080-9cc10b80-21d1-11ea-9a44-72314ad48835.png)

When i use the mac default screen capture, I get the correct screenshot with the windows present. I am running this script on my macbook pro 2014, so there is only 1 monitor. 

<img width="1280" alt="Screen Shot 2019-12-18 at 8 08 50 PM" src="https://user-images.githubusercontent.com/5833510/71136274-44d6d480-21d2-11ea-9b95-c3a84f7084d9.png">

### Full message

    N/A, the code runs fine.

### Other details

I tried using Pillows ImageGrab, and pyautogui, and I get the same result. I am wondering if Catalina changed some internal functionality when capturing screenshots.

**Comment by BoboTiG** [comment]
Catalina changed security settings. Did you ever encounter that: https://stackoverflow.com/q/59264255/1117028 ?

**Comment by interactivetech** [comment]
Thanks @BoboTiG for the response. The link helped me resolve the issue! I did not get an alert popup allowing mss to record contents, but changing the Privacy settings in the Screen Recording helped allow mss to capture the contents of my screen.

 When I go to System Preferences > Security & Privacy, I can select the Privacy Settings for Screen Recording. 
<img width="670" alt="Screen Shot 2019-12-19 at 10 06 27 AM" src="https://user-images.githubusercontent.com/5833510/71187122-6f657380-224c-11ea-87b7-70ea07aba65d.png">

I selected my code editor (Visual Studio Code) and my Terminal to have permission to  record the contents of my screen.

**Comment by hanskwan** [comment]
Same issue while screen cap with pyautogui, resolved with your solution thanks!

**Comment by pinnamaneni2005** [comment]
I am having same issue with pyautogui and the solution is not helping me. I am using jupyter notebook and I enabled screen recording for jupyter notebook also as in below image. But still not working.

![image](https://user-images.githubusercontent.com/72598602/124693620-6656f880-defd-11eb-93fc-1878af06892a.png)

**Comment by kaaass** [comment]
Grant screen record permission to the Terminal app (I use the Terminal app to run `latexocr`) solved the problem for me.

**Comment by kaaass** [comment]
My previous comment was not related to this issue. Sorry for the disturbance!
